<script lang="ts">
	import { Card, CardContent, CardHeader, CardTitle } from '$lib/components/ui/card';
	import { Badge } from '$lib/components/ui/badge';
	import { Skeleton } from '$lib/components/ui/skeleton';
	import { Alert, AlertDescription } from '$lib/components/ui/alert';
	import type { TastePrediction } from '$lib/types/taste';

	export let tastePrediction: TastePrediction | null;
	export let isGenerating = false;
	export let error: string | null = null;

	const tasteAttributes = [
		{ key: 'acidity', label: 'Acidity', icon: '🍋' },
		{ key: 'sweetness', label: 'Sweetness', icon: '🍯' },
		{ key: 'body', label: 'Body', icon: '☕' },
		{ key: 'clarity', label: 'Clarity', icon: '💎' },
		{ key: 'balance', label: 'Balance', icon: '⚖️' }
	] as const;

	function getConfidenceBadgeVariant(confidence: string) {
		switch (confidence) {
			case 'high':
				return 'default';
			case 'medium':
				return 'secondary';
			case 'low':
				return 'outline';
			default:
				return 'secondary';
		}
	}
</script>

<Card>
	<CardHeader>
		<div class="flex items-center justify-between">
			<CardTitle>AI Taste Prediction</CardTitle>
			{#if tastePrediction}
				<Badge variant={getConfidenceBadgeVariant(tastePrediction.confidence)}>
					{tastePrediction.confidence} confidence
				</Badge>
			{/if}
		</div>
	</CardHeader>
	<CardContent>
		{#if isGenerating}
			<div class="space-y-4">
				<Skeleton class="h-16 w-full" />
				<Skeleton class="h-16 w-full" />
				<Skeleton class="h-16 w-full" />
				<div class="text-center text-sm text-muted-foreground mt-4">
					Analyzing your recipe...
				</div>
			</div>
		{:else if error}
			<Alert variant="destructive">
				<AlertDescription>
					{error}
				</AlertDescription>
			</Alert>
		{:else if tastePrediction}
			<div class="space-y-4">
				{#each tasteAttributes as attr}
					<div class="rounded-lg border p-4">
						<div class="flex items-start gap-3">
							<span class="text-2xl">{attr.icon}</span>
							<div class="flex-1">
								<h4 class="font-semibold mb-1">{attr.label}</h4>
								<p class="text-sm text-muted-foreground leading-relaxed">
									{tastePrediction[attr.key]}
								</p>
							</div>
						</div>
					</div>
				{/each}

				<div class="mt-6 rounded-lg bg-muted p-4">
					<p class="text-xs text-muted-foreground">
						This taste prediction is generated by AI based on your coffee origin, roast level, and
						brewing parameters. Actual taste may vary based on bean freshness, water quality, and
						brewing technique.
					</p>
				</div>
			</div>
		{:else}
			<div class="text-center text-muted-foreground py-8">
				<p>Taste prediction will appear here after generating your recipe.</p>
			</div>
		{/if}
	</CardContent>
</Card>
