/**
 * Unit tests for TastePrediction component
 */

import { describe, it, expect } from 'vitest';
import { render } from '@testing-library/svelte';
import TastePrediction from '$lib/components/TastePrediction.svelte';
import type { TastePrediction as TastePredictionType } from '$lib/types/taste';

const mockTastePrediction: TastePredictionType = {
	acidity: 'Bright citrus notes with lime and bergamot',
	sweetness: 'Honeyed sweetness with floral undertones',
	body: 'Medium body with silky texture',
	clarity: 'Clean and clear flavor separation',
	balance: 'Well-balanced with harmonious acidity and sweetness',
	confidence: 'high'
};

describe('TastePrediction', () => {
	it('renders loading skeleton when isGenerating is true', () => {
		const { getByText, container } = render(TastePrediction, {
			props: { tastePrediction: null, isGenerating: true, error: null }
		});

		expect(getByText('Analyzing your recipe...')).toBeTruthy();
		const skeletons = container.querySelectorAll('.animate-pulse');
		expect(skeletons.length).toBeGreaterThan(0);
	});

	it('renders error alert when error provided', () => {
		const errorMessage = 'Failed to generate taste prediction';
		const { getByText } = render(TastePrediction, {
			props: { tastePrediction: null, isGenerating: false, error: errorMessage }
		});

		expect(getByText(errorMessage)).toBeTruthy();
	});

	it('renders placeholder when no prediction and not loading', () => {
		const { getByText } = render(TastePrediction, {
			props: { tastePrediction: null, isGenerating: false, error: null }
		});

		expect(getByText(/Taste prediction will appear here/)).toBeTruthy();
	});

	it('renders title', () => {
		const { getByText } = render(TastePrediction, {
			props: { tastePrediction: mockTastePrediction, isGenerating: false, error: null }
		});

		expect(getByText('AI Taste Prediction')).toBeTruthy();
	});

	it('displays confidence badge', () => {
		const { getByText } = render(TastePrediction, {
			props: { tastePrediction: mockTastePrediction, isGenerating: false, error: null }
		});

		expect(getByText('high confidence')).toBeTruthy();
	});

	it('renders all taste attributes', () => {
		const { getByText } = render(TastePrediction, {
			props: { tastePrediction: mockTastePrediction, isGenerating: false, error: null }
		});

		expect(getByText('Acidity')).toBeTruthy();
		expect(getByText('Sweetness')).toBeTruthy();
		expect(getByText('Body')).toBeTruthy();
		expect(getByText('Clarity')).toBeTruthy();
		expect(getByText('Balance')).toBeTruthy();
	});

	it('displays taste descriptions', () => {
		const { getByText } = render(TastePrediction, {
			props: { tastePrediction: mockTastePrediction, isGenerating: false, error: null }
		});

		expect(getByText(mockTastePrediction.acidity)).toBeTruthy();
		expect(getByText(mockTastePrediction.sweetness)).toBeTruthy();
		expect(getByText(mockTastePrediction.body)).toBeTruthy();
		expect(getByText(mockTastePrediction.clarity)).toBeTruthy();
		expect(getByText(mockTastePrediction.balance)).toBeTruthy();
	});

	it('displays disclaimer text', () => {
		const { getByText } = render(TastePrediction, {
			props: { tastePrediction: mockTastePrediction, isGenerating: false, error: null }
		});

		expect(getByText(/generated by AI/)).toBeTruthy();
		expect(getByText(/Actual taste may vary/)).toBeTruthy();
	});

	it('renders medium confidence badge', () => {
		const mediumConfidence: TastePredictionType = {
			...mockTastePrediction,
			confidence: 'medium'
		};

		const { getByText } = render(TastePrediction, {
			props: { tastePrediction: mediumConfidence, isGenerating: false, error: null }
		});

		expect(getByText('medium confidence')).toBeTruthy();
	});

	it('renders low confidence badge', () => {
		const lowConfidence: TastePredictionType = {
			...mockTastePrediction,
			confidence: 'low'
		};

		const { getByText } = render(TastePrediction, {
			props: { tastePrediction: lowConfidence, isGenerating: false, error: null }
		});

		expect(getByText('low confidence')).toBeTruthy();
	});

	it('displays emoji icons for each attribute', () => {
		const { getByText } = render(TastePrediction, {
			props: { tastePrediction: mockTastePrediction, isGenerating: false, error: null }
		});

		expect(getByText('🍋')).toBeTruthy(); // Acidity
		expect(getByText('🍯')).toBeTruthy(); // Sweetness
		expect(getByText('☕')).toBeTruthy(); // Body
		expect(getByText('💎')).toBeTruthy(); // Clarity
		expect(getByText('⚖️')).toBeTruthy(); // Balance
	});
});
